README.md
Everything seems to work fine in VS Code, by using the existing "Nix IDE" extension and just setting the correct binary.
It might be useful to mention it in the readme.
=> Add instructions for vscode

crates/ide/src/ty/known.rs
nil was giving me questionable completions - `packages.default` is not supposed to be a derivation, `packages.${system}.default` is. This PR fixes this issue for `packages` and `devShells`, and also fixes and improves types for `nixosConfigurations`. I wasn't able to get completion working correctly, but that seems to be a separate issue since I also couldn't get `inputs.*.inputs.*` to complete `follows`
=> Fix and improve types for flake outputs

crates/ide/src/ide/assists/mod.rs, crates/ide/src/ide/assists/rewrite_string.rs, docs/code_actions.md
https://github.com/oxalica/nil/issues/39#issuecomment-1338882949
=> Add string rewriting assists

.github/workflows/ci.yaml, Cargo.toml, crates/ide/src/base.rs, crates/ide/src/def/tests.rs, crates/ide/src/tests.rs, crates/ide/src/ty/convert.rs, crates/ide/src/ty/infer.rs, crates/ide/src/ty/known.rs, crates/ide/src/ty/mod.rs, crates/ide/src/ty/tests.rs, crates/nil/Cargo.toml, crates/nil/src/server.rs, crates/nix-interop/Cargo.toml, crates/nix-interop/src/flake_output.rs, crates/nix-interop/src/info.rs, crates/nix-interop/src/lib.rs, crates/nix-interop/src/version.rs, dev/nvim-lsp.nix, dev/vim-coc.nix, dev/vimrc.vim, flake.lock
=> Eval and inject types for input flakes

crates/nix-interop/src/nixos_options.nix
so nil doesn't output an error when with something like this: `inputs.nixpkgs.url = "github:nix-community/nixpkgs.lib";`
=> Don't look for NixOS options when module-list.nix or lib doesn't exist

crates/nil/src/server.rs
Allows to configure the server when client doesn't support `workspace/configuration` method, for example, LanguageClient-neovim.
=> Load configuration during initialize handling

crates/nil/src/capabilities.rs, crates/nil/src/server.rs
Don't send it to clients (like LanguageClient-neovim) that don't support it to avoid error noise.
=> Check if workspace/configuration is supported

crates/ide/src/diagnostic.rs, crates/nil/src/main.rs, docs/features.md
Thanks for this amazing project! :heart: 
Would love to be able to ignore warnings for the [pre-commit hook in my devenv](https://github.com/cachix/pre-commit-hooks.nix/blob/master/modules/hooks.nix#L774)
=> Diagnostics CLI: return different exit code when only warnings

crates/nil/src/server.rs
I believe this is a typo since 'flake_files_changed' should probably be initialised to false for the condition to 'spawn_load_flake_workspaces' to make any sense.
=> Condition always evaluates to true

crates/nil/src/server.rs
It took me a while to find out what auto-fetch actually means from my lsp client log. There's no such thing as auto-fetch, it's autoArhive.
Somebody else entered this as well. https://www.reddit.com/r/neovim/comments/14pk1u5/lsp_tells_me_to_enable_autofetch_in/
=> Rewording warning message

crates/builtin/build.rs
Closes #93 
Should be fully backwards compatible.
Tested both on nix master 2.17 prerelease and nix 2.16 - builds fine on both!
=> fix: fix build on nix 2.17

.github/workflows/ci.yaml, crates/ide/src/ide/hover.rs, flake.lock
Updates nixpkgs so nil builds with nix 2.17 and fixes the test expectations.
=> Fix tests for nix 2.17

crates/nil/src/vfs.rs
This PR fixes a bug, which converts the offset to a wrong line/col at the end of the file. 
E.g. for "x", offset 1 is converted to line 1 col 0, instead of line 0 col 1.
=> Fix offset conversion for end of file

crates/nix-interop/src/nixos_options.nix
a.k.a. fix a small typo.
Because the type-name `attrsOf` was never matched, e.g. `systemd.services` always had type `any`.
cc @oxalica
=> nix-interop: fix option completion of `types.attrsOf (types.submodule {})`

crates/nil/src/handler.rs
Currently, nil silently fails when no formatter is set. This caused me a lot of confusion as to why nothing was formatting when I accidentally misconfigured the formatter.
This makes it so that we return an error instead, alerting the user that something is wrong.
This could be annoying to someone who hasn't configured a formatter on purpose but still causes formatting events, either by format-on-save or muscle memory. I think this is fine, and they should turn off format-on-save or just get a formatter instead. Alternatively, someone could set `cat` as their formatter.
> [Error - 8:02:06 PM] Request textDocument/formatting failed.
>  Message: No formatter configured. Set the nil.formatting.command LSP server setting.
>  Code: -32603
=> Fail textDocument/formatting when no formatter is set

crates/nil/Cargo.toml
> `default_features` is deprecated in favor of `default-features` and will not work in the 2024 edition
=> Cargo.toml: Rename from `default_features` to `default-features`

crates/ide/src/ty/known.rs
Hello there 👋!
The NixOS wiki is in the process of migrating from https://nixos.wiki to https://wiki.nixos.org.
You can find more information about it [here](https://github.com/NixOS/foundation/issues/113).
You seem to be using the old link in your repository, which is why we send you this PR.
If you feel like this is not correct or have any questions, feel free to [get in touch with us](https://github.com/NixOS/nixos-wiki-infra/issues/105).
Have a great day,
-- The NixOS Wiki-Team ❄️
=> Update NixOS Wiki link

crates/ide/src/ide/links.rs
There's no reason to strip these values for non-flake refs, as the comment here itself states: "Trim `?` and `#` parts, which are special *for flake-ref*." Instead, this behavior was breaking the ability to open other non-flake ref links, like the following from the `vscode-extensions` section of Nixpkgs where essential query parameters were stripped:
=> Only strip query parameters and fragment for flake ref URLs

README.md
Hi
I'm author of lsp-bridge https://github.com/manateelazycat/lsp-bridge/
I have attach patch to support nil in lsp-bridge, thanks for merge. ;)
=> Add lsp-bridge in Emacs doc

.github/workflows/ci.yaml, dev/flake.lock, dev/flake.nix, dev/pre-push.sh, flake.lock, flake.nix
This removes dev-dependencies from main `flake.nix`, so users of the main flake does not need to pull them in.
=> Split out devShells dependenties to dev/flake.nix

crates/ide/src/ide/inlay_hints.rs, crates/ide/src/ide/mod.rs, crates/ide/src/lib.rs, crates/nil/src/capabilities.rs, crates/nil/src/config.rs, crates/nil/src/convert.rs, crates/nil/src/handler.rs, crates/nil/src/server.rs, docs/features.md
Attempt to implement #166.
I haven't figured out the best way to match on the ast.
It would be nice to match on the shape `{ attrName = <expr> ; }`, where we display `attrName` right after `<expr>` or the semicolon.
=> Feat: Inlay hints on the end of let/attrset bindings

crates/ide/src/ty/infer.rs
The code simply did not have a match for the lists, so for example, for which configuration there were no suggestions.
```nix
settings = lib.mkOption {
type = lib.types.listOf (lib.types.submodule {
options = {
logLevel = lib.mkOption {
type = lib.types.enum ["debug" "info" "warn" "error"];
default = "info";
};
};
});
default = {};
};
```
```nix
{
settings = [ {
<CURSOR FOR SUGGESTION>
} ];
}
```
After this fix, logLevel is suggested.
=> Fix the infer of list object types
